language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install Cython
  - pip install netcdf4
#  - pip install pytest
#  - pip install matplotlib

script:
  - python setup.py build_ext --inplace
  - py.test -s -v tests

